version: 2
updates:
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: daily
      open-pull-requests-limit: 10
      ignore:
          - dependency-name: "@angular/platform-browser-dynamic"
            versions:
                - 11.2.11
